# Configuration for the entire ML pipeline
python_executable: '/opt/anaconda3/envs/KiteConnect/bin/python'

#---------------------------------------------------
# 1. DATA & FEATURE GENERATION
#---------------------------------------------------
data:
  training_start_date: '2021-05-01'
  training_end_date: '2024-05-30'
  validation_end_date: '2024-06-01'
  test_end_date: '2025-06-27'
  token_list_query: "with penny_stocks as ( Select distinct a.instrument_token from kiteconnect.historical_data_day a where (close*volume < 2000000 or volume < 200000) and timestamp >= DATE_FORMAT(CURDATE() - INTERVAL 30 DAY, '%Y-%m-%d') ) Select distinct instrument_token FROM kiteconnect.instruments_zerodha a WHERE instrument_type = 'EQ' AND lower(name) NOT LIKE '%nifty%' and instrument_token not in (Select * from penny_stocks) AND lot_size = 1"
  # nifty_50_token: 256265

target_generation:
  lookahead_candles: 7
  threshold_percent: 10.0
  stop_loss_pct: 4.0
  
#---------------------------------------------------
# 4. COMPOSITE BACKTESTING
#---------------------------------------------------
backtest:
  holding_period: 7
  target_price_pct: 20.0
  stop_loss_pct: 4.0

#---------------------------------------------------
# 2. MODELING
#---------------------------------------------------
modeling:
  strategies_to_train: ['combined']
  targets: ['target_up', 'target_down']
  model_types: ['catboost']
  # targets: ['target_up', 'target_down']
  # strategies_to_train: ['combined']
  # model_types: ['catboost']
  random_state: 42

#---------------------------------------------------
# 3. BACKTESTING
#---------------------------------------------------
trading:
  # A list of probability thresholds to test for PnL evaluation.
  backtest_thresholds: [0.70] 
  # backtest_thresholds: [0.60] 

  # --- Simulation Settings ---
  simulation_params:
    initial_capital: 500000
    transaction_cost_pct: 0.0
    capital_per_trade: 50000
